# 1. Create a 3x3x3 array with random values 

In [8]:
import numpy as np
x=np.random.random((3,3,3))
print(x)

[[[0.72968623 0.73222536 0.32075683]
  [0.47726905 0.72517007 0.71687316]
  [0.66042041 0.28028345 0.93818516]]

 [[0.33458957 0.36821122 0.50548105]
  [0.72590397 0.02892364 0.28830101]
  [0.73700929 0.77121003 0.87236329]]

 [[0.47558539 0.71931847 0.89759966]
  [0.68061797 0.5802795  0.30060035]
  [0.16483655 0.37722846 0.59003892]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [10]:
import numpy as np
x=np.diag([1,2,3,4])
print(x)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [13]:
import numpy as np 
x=np.ones((3,3))
print( "checkerboard pattern")
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
print(x)

checkerboard pattern
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [18]:
import numpy as np
x=np.random.random((5,5))
print("original array:")
print(x)
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
print("After normalization:")
print(x)

original array:
[[0.71087878 0.50557545 0.13696498 0.35886545 0.62428058]
 [0.01874061 0.06447554 0.80206398 0.73028059 0.77959639]
 [0.06569883 0.66666215 0.99349459 0.34842207 0.96201523]
 [0.00938222 0.57813635 0.45937695 0.41346685 0.41501581]
 [0.32253078 0.56266154 0.13793168 0.83703834 0.54464332]]
After normalization:
[[0.71282161 0.50420384 0.12964247 0.35512533 0.62482535]
 [0.00950947 0.05598275 0.80547892 0.73253665 0.7826486 ]
 [0.05722579 0.66789114 1.         0.34451335 0.96801243]
 [0.         0.57793617 0.4572595  0.41060822 0.41218219]
 [0.31820407 0.56221153 0.13062477 0.8410179  0.54390242]]


# 5.  How to find common values between two arrays?

In [19]:
import numpy as np
arr1=np.array([10,20,30,70])
print("Array:",arr1)
arr2=np.array([10,20,36,78])
print("Array:",arr2)
print("common values between two arrays:")
print(np.intersect1d(arr1,arr2))


Array: [10 20 30 70]
Array: [10 20 36 78]
common values between two arrays:
[10 20]


# 6.How to get the dates of yesterday, today and tomorrow?

In [1]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [2]:
import numpy as np
x = np.random.randint(0,2,6)
print("1st array:")
print(x)
y = np.random.randint(0,2,6)
print("2nd array:")
print(y)
print("Test above two arrays are equal or not!")
array_equal = np.allclose(x, y)
print(array_equal)

1st array:
[0 0 1 1 0 1]
2nd array:
[1 0 1 1 1 0]
Test above two arrays are equal or not!
False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [5]:
import numpy as np
x = np.random.random(15)
print("Original array:")
print(x)
x[x.argmax()] = -1
print("Maximum value replaced by -1:")
print(x)


Original array:
[0.79594378 0.35529432 0.51167464 0.35718579 0.49137985 0.15214919
 0.05727339 0.63363191 0.99470716 0.03551784 0.81468172 0.23063163
 0.14724703 0.48526191 0.31466179]
Maximum value replaced by -1:
[ 0.79594378  0.35529432  0.51167464  0.35718579  0.49137985  0.15214919
  0.05727339  0.63363191 -1.          0.03551784  0.81468172  0.23063163
  0.14724703  0.48526191  0.31466179]


# 9. How to print all the values of an array?

In [9]:
my_array = np. arange(100)
print(my_array)
np. set_printoptions(threshold=np. inf)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


# 10.Subtract the mean of each row of a matrix

In [11]:
import numpy as np
print("Original matrix:\n")
X = np.random.rand(2, 5)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


Original matrix:

[[0.85939765 0.94644979 0.89582155 0.64829949 0.10306391]
 [0.67424526 0.69713434 0.07730091 0.64346418 0.31307811]]

Subtract the mean of each row of the said matrix:

[[ 0.16879117  0.25584331  0.20521507 -0.04230699 -0.58754257]
 [ 0.1932007   0.21608978 -0.40374365  0.16241962 -0.16796645]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [12]:
Z = np.ones(10)

I = np.random.randint(0,len(Z),20)

Z += np.bincount(I, minlength=len(Z))

print(Z)

[1. 1. 4. 6. 3. 3. 3. 3. 4. 2.]


In [13]:
np.add.at(Z, I, 1)

print(Z)

[ 1.  1.  7. 11.  5.  5.  5.  5.  7.  3.]


# 12.How to get the diagonal of a dot product?

In [23]:
x = np.random.uniform(0,1,(5,5))

y = np.random.uniform(0,1,(5,5))
np.sum(x * y.T, axis=1)

array([0.61957886, 1.44640336, 1.07865547, 1.27570924, 0.82673813])

# 13.How to find the most frequent value in an array?

In [7]:
import numpy as np
arr=[99,88,67,55,36,298,88,536,784,937]
a=np.bincount(arr).argmax()
print("largest value of array:",a)


largest value of array: 88


# 14.How to get the n largest values of an array

In [4]:
import numpy as np
arr=[99,88,67,55,36,298,536,784,937]
a=np.max(arr)
print("largest value of array:",a)


largest value of array: 937


# 15.How to create a record array from a regular array?

In [22]:
import numpy as np
a1=np.array([1,2,3,4])
a2=np.array(['Red','Green','White','Orange'])
a3=np.array([12.20,15,20,40])
result= np.core.records.fromarrays([a1, a2, a3],names='a,b,c')
print(result[0])
print(result[1])
print(result[2])

(1, 'Red', 12.2)
(2, 'Green', 15.)
(3, 'White', 20.)
